### ISSUE TITLE
Deployed to the server, not to display the directly, I use a meteor development, using the meteor up deployment, but it is no problem running locally

### ISSUE THREAD

**Issue by guoyoujin** [jshimko/meteor-ghostdown#10]
Deployed to the server, not to display the directly, I use a meteor development, using the meteor up deployment, but it is no problem running locally：http://yoyjinguo.meteor.com/

**Comment by jshimko** [comment]
I unfortunately can't give you any suggestions without more information than that.  It looks like a lot more things are broken than just the editor.

![yoyjinguo](https://cloud.githubusercontent.com/assets/3077956/8922123/ec996a1a-34ac-11e5-901e-9a2a68d34277.jpg)

**Comment by guoyoujin** [comment]
@jshimko Thank you very much, I found I have from your screenshot out of wrong, I should review, ignoring the chrome debugging, you gave me great help, thank you very much, the problem has been solved
