### ISSUE TITLE
Is there a way to force the container to be full width?

### ISSUE THREAD

**Issue by abhisheksoni27** [jshimko/meteor-ghostdown#7]
I searched the css, and was able to get the border width to 1px, but the issue, the container, has some padding, onright, left and bottom. I am talking about the main editor, which is given postion:absolute attribute. If maybe, that was changed and the widht could be set to 100%? Now the bottom padding is fine, but if there was a way to change the right and left margins, or padding?

**Comment by jshimko** [comment]
There isn't any CSS included in this package, so I'm not sure what you searched (I assume you mean your own styles).  This package is currently just the functionality with no styling.  

That said, you can add any CSS you'd like to customize the layout.  Take a look at the template markup (mentioned in the README) and use the classes in that to style the editor the way you want.

**Comment by abhisheksoni27** [comment]
I was talking about the CSS used in demo app. I managed to achieve it, and I will issue a pull-request.

**Comment by jshimko** [comment]
Great!  Glad you figured it out.  Definitely open to any contributions.  This editor has been on my back burner for a while now, but I definitely want to make it a little more flexible since it appears a lot of people are using it.
